#*****************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# top_demo_uoe.tcl: Tcl script for re-creating project 'top_demo_uoe'
#
# Generated by Vivado on Mon Jul 28 09:53:49 +0200 2025
# IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (top_demo_uoe.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_utils_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/arbiter_binary.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/arbiter_onehot.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/dev_utils_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/dev_utils_2008_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axi4lite_utils_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axi4lite_onereq.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axi4lite_register.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axi4lite_sp_ram_ctrl.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axi4lite_switch.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_broadcast.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_broadcast_custom.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_combine.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_demux.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_demux_custom.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_demux_notdest.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_dwidth_converter.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_enable.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/cdc_utils_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/memory_utils_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_fifo.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/datatest_tools_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_frame_chk.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_monitor.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_mux_custom.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_mux_noarb_binary.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_mux_noarb_onehot.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_pkt_align.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_pkt_chk.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_pkt_drop.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_pkt_gen.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_rate_limit.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/axis_register.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/bridge_ascii_to_axi4lite.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/cdc_bit_sync.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/cdc_gray_sync.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/cdc_pulse_sync.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/cdc_reset_sync.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/fifo_gen.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/prbs_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/gen_prbs.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/gen_ramp.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/gig_ethernet_pcs_pma_sfp_resets.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/interruptions.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/package_demo_registers.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/main_demo_registers.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/main_demo_registers_itf.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/package_uoe_registers.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/main_uoe_registers.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/main_uoe_registers_itf.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/serial_if_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/sfp_1g.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/sfp_interfaces.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/simple_dp_ram.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/test_uoe_registers.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/test_uoe_registers_itf.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_module_pkg.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/top_uoe.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/common/true_dp_ram.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/uart_if.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_cache.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_controller.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_module.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_module_disable_protocol.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_rx_protocol.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_table.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_table_memory.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_arp_tx_protocol.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_core.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_frame_router.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_frame_switch.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_frame_switch_tdest.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_generic_filter.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_integrated_tests_mac.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_integrated_tests_udp.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_internet_layer.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_ipv4_module.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_ipv4_module_tx.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_link_layer.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_mac_filter.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_mac_shaping.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_mac_shaping_tx.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_transport_layer.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_udp_module.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_udp_module_tx.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/src/vhdl/top_demo_uoe.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/uoe_config.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/src/uoe_module/wrapped_uoe_core.vhd"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/gig_ethernet_pcs_pma_sfp_ch2/gig_ethernet_pcs_pma_sfp_ch2.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/jtag_axi/jtag_axi.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/vio_rx_1G_cfg/vio_rx_1G_cfg.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/tri_mode_ethernet_mac_1g/tri_mode_ethernet_mac_1g.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/vio_tx_1G_cfg/vio_tx_1G_cfg.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/ip/clk_wiz_design/clk_wiz_design.xci"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/constrs/cdc_bit_sync.xdc"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/constrs/cdc_gray_sync.xdc"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/constrs/cdc_reset_sync.xdc"
#    "C:/Users/lima/Desktop/Thales-Ganil/udp-offload-engine/examples/KCU105/constrs/top_demo_uoe.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "top_demo_uoe"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "top_demo_uoe.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/top_demo_uoe"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcku040-ffva1156-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "corecontainer.enable" -value "1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_core_container" -value "1" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcku040-ffva1156-2-e" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../src/common/axis_utils_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/arbiter_binary.vhd"] \
 [file normalize "${origin_dir}/../../src/common/arbiter_onehot.vhd"] \
 [file normalize "${origin_dir}/../../src/common/dev_utils_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/dev_utils_2008_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axi4lite_utils_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axi4lite_onereq.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axi4lite_register.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axi4lite_sp_ram_ctrl.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axi4lite_switch.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_broadcast.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_broadcast_custom.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_combine.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_demux.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_demux_custom.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_demux_notdest.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_dwidth_converter.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_enable.vhd"] \
 [file normalize "${origin_dir}/../../src/common/cdc_utils_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/memory_utils_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_fifo.vhd"] \
 [file normalize "${origin_dir}/../../src/common/datatest_tools_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_frame_chk.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_monitor.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_mux_custom.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_mux_noarb_binary.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_mux_noarb_onehot.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_pkt_align.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_pkt_chk.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_pkt_drop.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_pkt_gen.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_rate_limit.vhd"] \
 [file normalize "${origin_dir}/../../src/common/axis_register.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/bridge_ascii_to_axi4lite.vhd"] \
 [file normalize "${origin_dir}/../../src/common/cdc_bit_sync.vhd"] \
 [file normalize "${origin_dir}/../../src/common/cdc_gray_sync.vhd"] \
 [file normalize "${origin_dir}/../../src/common/cdc_pulse_sync.vhd"] \
 [file normalize "${origin_dir}/../../src/common/cdc_reset_sync.vhd"] \
 [file normalize "${origin_dir}/../../src/common/fifo_gen.vhd"] \
 [file normalize "${origin_dir}/../../src/common/prbs_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/common/gen_prbs.vhd"] \
 [file normalize "${origin_dir}/../../src/common/gen_ramp.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/gig_ethernet_pcs_pma_sfp_resets.vhd"] \
 [file normalize "${origin_dir}/../../src/common/interruptions.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/package_demo_registers.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/main_demo_registers.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/main_demo_registers_itf.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/package_uoe_registers.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/main_uoe_registers.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/main_uoe_registers_itf.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/serial_if_pkg.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/sfp_1g.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/sfp_interfaces.vhd"] \
 [file normalize "${origin_dir}/../../src/common/simple_dp_ram.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/test_uoe_registers.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/test_uoe_registers_itf.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_module_pkg.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/top_uoe.vhd"] \
 [file normalize "${origin_dir}/../../src/common/true_dp_ram.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/uart_if.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_cache.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_controller.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_module.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_module_disable_protocol.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_rx_protocol.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_table.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_table_memory.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_arp_tx_protocol.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_core.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_frame_router.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_frame_switch.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_frame_switch_tdest.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_generic_filter.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_integrated_tests_mac.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_integrated_tests_udp.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_internet_layer.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_ipv4_module.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_ipv4_module_tx.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_link_layer.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_mac_filter.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_mac_shaping.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_mac_shaping_tx.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_transport_layer.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_udp_module.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_udp_module_tx.vhd"] \
 [file normalize "${origin_dir}/src/vhdl/top_demo_uoe.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/uoe_config.vhd"] \
 [file normalize "${origin_dir}/../../src/uoe_module/wrapped_uoe_core.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../../src/common/axis_utils_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/arbiter_binary.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/arbiter_onehot.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/dev_utils_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/dev_utils_2008_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axi4lite_utils_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axi4lite_onereq.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axi4lite_register.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axi4lite_sp_ram_ctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axi4lite_switch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_broadcast.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_broadcast_custom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_combine.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_demux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_demux_custom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_demux_notdest.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_dwidth_converter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_enable.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/cdc_utils_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/memory_utils_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_fifo.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/datatest_tools_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_frame_chk.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_monitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_mux_custom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_mux_noarb_binary.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_mux_noarb_onehot.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_pkt_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_pkt_chk.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_pkt_drop.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_pkt_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_rate_limit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/axis_register.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/src/vhdl/bridge_ascii_to_axi4lite.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/common/cdc_bit_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/cdc_gray_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/cdc_pulse_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/cdc_reset_sync.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/fifo_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/prbs_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/gen_prbs.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/common/gen_ramp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/src/vhdl/gig_ethernet_pcs_pma_sfp_resets.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/common/interruptions.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/src/vhdl/package_demo_registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/src/vhdl/main_demo_registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/src/vhdl/main_demo_registers_itf.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/package_uoe_registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/main_uoe_registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/main_uoe_registers_itf.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/src/vhdl/serial_if_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/src/vhdl/sfp_1g.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/src/vhdl/sfp_interfaces.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/common/simple_dp_ram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/test_uoe_registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/test_uoe_registers_itf.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_module_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/top_uoe.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/common/true_dp_ram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "common" -objects $file_obj

set file "$origin_dir/src/vhdl/uart_if.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_cache.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_module_disable_protocol.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_rx_protocol.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_table.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_table_memory.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_arp_tx_protocol.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_frame_router.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_frame_switch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_frame_switch_tdest.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_generic_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_integrated_tests_mac.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_integrated_tests_udp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_internet_layer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_ipv4_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_ipv4_module_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_link_layer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_mac_filter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_mac_shaping.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_mac_shaping_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_transport_layer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_udp_module.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_udp_module_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/src/vhdl/top_demo_uoe.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "design" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/uoe_config.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj

set file "$origin_dir/../../src/uoe_module/wrapped_uoe_core.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "uoe_module" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top_demo_uoe" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/gig_ethernet_pcs_pma_sfp_ch2/gig_ethernet_pcs_pma_sfp_ch2.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/gig_ethernet_pcs_pma_sfp_ch2/gig_ethernet_pcs_pma_sfp_ch2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/jtag_axi/jtag_axi.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/jtag_axi/jtag_axi.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/vio_rx_1G_cfg/vio_rx_1G_cfg.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/vio_rx_1G_cfg/vio_rx_1G_cfg.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/tri_mode_ethernet_mac_1g/tri_mode_ethernet_mac_1g.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/tri_mode_ethernet_mac_1g/tri_mode_ethernet_mac_1g.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/vio_tx_1G_cfg/vio_tx_1G_cfg.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/vio_tx_1G_cfg/vio_tx_1G_cfg.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/clk_wiz_design/clk_wiz_design.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/clk_wiz_design/clk_wiz_design.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/cdc_bit_sync.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/cdc_bit_sync.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "processing_order" -value "LATE" -objects $file_obj
set_property -name "scoped_to_ref" -value "cdc_bit_sync" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/cdc_gray_sync.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/cdc_gray_sync.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "processing_order" -value "LATE" -objects $file_obj
set_property -name "scoped_to_ref" -value "cdc_gray_sync" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/cdc_reset_sync.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/cdc_reset_sync.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "processing_order" -value "LATE" -objects $file_obj
set_property -name "scoped_to_ref" -value "cdc_reset_sync" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/top_demo_uoe.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/top_demo_uoe.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcku040-ffva1156-2-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "top_demo_uoe" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "design" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcku040-ffva1156-2-e -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcku040-ffva1156-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcku040-ffva1156-2-e -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xcku040-ffva1156-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
